language: c
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y pkg-config libtool autopoint gettext lcov zlib1g-dev libbz2-dev liblzma-dev libselinux1-dev libncursesw5-dev perl libio-string-perl libdevel-cover-perl
before_script:
  - sudo cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
script:
  - autoreconf -f -i && ./configure --enable-coverage && make check
after_success:
  - find lib/dpkg/t src/t utils/t -name '*.gcda' -o -name '*.gcov' | xargs rm -f
  - bash <(curl -s https://codecov.io/bash)
  - cd scripts && /usr/bin/cover -ignore_re '^t/.*\.t' -report codecov
